openapi: 3.0.0
info:
  title: Gestión del Carrito de Compras
  description: API para gestionar el carrito de compras, incluyendo la creación, actualización, compra y eliminación de productos del carrito.
  version: 1.0.0

paths:
  /api/carts/{userId}:
    post:
      tags:
        - carrito
      summary: Obtiene el carrito de un usuario.
      description: Retorna el carrito asociado al usuario dado su ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID único del usuario cuyo carrito se desea obtener.
          schema:
            type: string
            example: "60f73f1c8d2a8b6f1c9c5d7a"
      responses:
        '200':
          description: Un objeto JSON con el carrito del usuario.
          content:
            application/json:
              schema:
                type: object
                properties:
                  carrito:
                    type: object
                    description: El carrito del usuario.
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error interno del servidor."

  /api/carts/addProduct/{cid}:
    post:
      tags:
        - carrito
      summary: Agrega un producto al carrito.
      description: Añade un producto al carrito especificado por su ID.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID único del carrito al que se desea añadir el producto.
          schema:
            type: string
            example: "60f73f1c8d2a8b6f1c9c5d7a"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                producto:
                  type: object
                  description: Los datos del producto a añadir.
                  example:
                    title: "Teclado"
                    price: 50
                    quantity: 2
      responses:
        '200':
          description: Un objeto JSON con el carrito actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  carrito:
                    type: object
                    description: El carrito actualizado.
        '400':
          description: Error en el envío del producto o en la actualización del carrito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se recibió el producto."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error interno del servidor."

  /api/carts/purchase/{cid}:
    post:
      tags:
        - carrito
      summary: Realiza una compra del carrito.
      description: Procesa la compra del carrito especificado por su ID y retorna un mensaje de éxito.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID único del carrito a comprar.
          schema:
            type: string
            example: "60f73f1c8d2a8b6f1c9c5d7a"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  productId:
                    type: string
                    description: ID del producto en el carrito.
                    example: "60f73f1c8d2a8b6f1c9c5d7b"
                  quantity:
                    type: number
                    description: Cantidad del producto.
                    example: 1
      responses:
        '200':
          description: Mensaje confirmando la compra del carrito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  payload:
                    type: object
                    properties:
                      carritoId:
                        type: string
                        example: "60f73f1c8d2a8b6f1c9c5d7a"
                      amount:
                        type: number
                        example: 150
                      mensaje:
                        type: string
                        example: "Compra realizada con éxito."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error interno del servidor."

  /api/carts/{cid}/deleteProduct/{pid}:
    delete:
      tags:
        - carrito
      summary: Elimina un producto del carrito.
      description: Elimina un producto del carrito especificado por su ID de carrito y ID de producto.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID único del carrito del cual se eliminará el producto.
          schema:
            type: string
            example: "60f73f1c8d2a8b6f1c9c5d7a"
        - name: pid
          in: path
          required: true
          description: ID único del producto a eliminar.
          schema:
            type: string
            example: "60f73f1c8d2a8b6f1c9c5d7b"
      responses:
        '200':
          description: Un objeto JSON con el carrito actualizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  carrito:
                    type: object
                    description: El carrito actualizado.
        '404':
          description: El carrito o el producto no fueron encontrados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "El carrito con Id: 60f73f1c8d2a8b6f1c9c5d7a no existe."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error interno del servidor."
